## 4.3 데이터 조작 ( Data Manipulation )

#### 4.3.1 시작하기

In [3]:
import mxnet as mx 
from mxnet import nd

In [4]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [5]:
x.shape

(12,)

In [6]:
x.size

12

In [11]:
x.reshape((3, 4))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [13]:
x.reshape((3,-1))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [17]:
x.reshape((4,-1))


[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
<NDArray 4x3 @cpu(0)>

In [18]:
nd.empty((3,4))


[[0.000000e+00 2.000000e+00 0.000000e+00 2.000000e+00]
 [1.261169e-44 0.000000e+00 4.014500e+06 4.574259e-41]
 [4.014500e+06 4.574259e-41 2.745716e+06 4.574259e-41]]
<NDArray 3x4 @cpu(0)>

In [19]:
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [20]:
nd.ones((2,3,4))


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
<NDArray 2x3x4 @cpu(0)>

In [22]:
y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [23]:
nd.random.normal(0, 1, shape=(3, 4))


[[ 1.1630787   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546344  -0.54877394]]
<NDArray 3x4 @cpu(0)>

----

#### 4.3.2 연산들

In [10]:
x = nd.array([1,2,4,8])
y = nd.ones_like(x) * 2
print('x =', x)
print('y =', y)
print('x + y', x + y) 
print('x - y', x - y)
print('x * y', x * y)
print('x / y', x / y)

x = 
[1. 2. 4. 8.]
<NDArray 4 @cpu(0)>
y = 
[2. 2. 2. 2.]
<NDArray 4 @cpu(0)>
x + y 
[ 3.  4.  6. 10.]
<NDArray 4 @cpu(0)>
x - y 
[-1.  0.  2.  6.]
<NDArray 4 @cpu(0)>
x * y 
[ 2.  4.  8. 16.]
<NDArray 4 @cpu(0)>
x / y 
[0.5 1.  2.  4. ]
<NDArray 4 @cpu(0)>


In [11]:
x.exp()


[2.7182817e+00 7.3890562e+00 5.4598148e+01 2.9809580e+03]
<NDArray 4 @cpu(0)>

In [28]:
x = nd.arange(12).reshape((3,4))
y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
nd.dot(x, y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [13]:
print(nd.concat(x, y, dim=0))
print(nd.concat(x, y, dim=1))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>

[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>


In [14]:
x == y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [15]:
x.sum()


[66.]
<NDArray 1 @cpu(0)>

In [16]:
x.norm().asscalar()

22.494442

----

#### 4.3.3 브로드케스트 메카니즘

In [17]:
a = nd.arange(3).reshape((3, 1))
b = nd.arange(2).reshape((1, 2))
a, b

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [24]:
a + b


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

----

#### 4.3.4 인덱싱과 슬라이싱(slicing)

In [29]:
x[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [30]:
x[1, 2] = 9
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [31]:
x[0:2, :] = 12
x


[[12. 12. 12. 12.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

----

#### 4.3.5 메모리 절약하기

In [54]:
before = id(y)
y=y+x
id(y) == before

False

In [55]:
z = y.zeros_like()
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 140201865294256
id(z): 140201865294256


In [56]:
before = id(z)
nd.elemwise_add(x, y, out=z)
id(z) == before

True

----

#### 4.3.6 NDArray와 NumPy간 상호 변환

In [57]:
import numpy as np
a = x.asnumpy()
print(type(a))
b = nd.array(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'mxnet.ndarray.ndarray.NDArray'>


----

## 4.4 선형대수

In [58]:
from mxnet import nd

#### 4.4.1 스칼라(scalar)

In [60]:
x = nd.array([3.0])
y = nd.array([2.0])
print('x + y = ', x + y)
print('x * y = ', x * y)
print('x / y = ', x / y)
print('x ** y = ', nd.power(x,y))

x + y =  
[5.]
<NDArray 1 @cpu(0)>
x * y =  
[6.]
<NDArray 1 @cpu(0)>
x / y =  
[1.5]
<NDArray 1 @cpu(0)>
x ** y =  
[9.]
<NDArray 1 @cpu(0)>


In [61]:
x.asscalar()

3.0

----

#### 4.4.2 벡터(vector)

In [62]:
x = nd.arange(4)
print('x = ', x)

x =  
[0. 1. 2. 3.]
<NDArray 4 @cpu(0)>


In [63]:
x[3]


[3.]
<NDArray 1 @cpu(0)>

----

#### 4.4.3 길이, 차원(dimensionality), 모양(shape)

In [51]:
x.shape

(4,)

In [4]:
a=2
x = nd.array([1,2,3])
y = nd.array([10,20,30]) 
print(a * x)
print(a * x + y)


[2. 4. 6.]
<NDArray 3 @cpu(0)>

[12. 24. 36.]
<NDArray 3 @cpu(0)>


----

#### 4.4.4 행렬(matrix)

In [5]:
A = nd.arange(20).reshape((5,4))
print(A)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
<NDArray 5x4 @cpu(0)>


In [35]:
print(A.T)


[[ 0.  4.  8. 12. 16.]
 [ 1.  5.  9. 13. 17.]
 [ 2.  6. 10. 14. 18.]
 [ 3.  7. 11. 15. 19.]]
<NDArray 4x5 @cpu(0)>


----

#### 4.4.5 텐서(tensor)

In [36]:
X = nd.arange(24).reshape((2, 3, 4))
print('X.shape =', X.shape)
print('X =', X)

X.shape = (2, 3, 4)
X = 
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
<NDArray 2x3x4 @cpu(0)>


----

#### 4.4.6 텐서 연산의 기본 성질

In [37]:
a=2
x = nd.ones(3)
y = nd.zeros(3)
print(x.shape)
print(y.shape)
print((a * x).shape)
print((a * x + y).shape)

(3,)
(3,)
(3,)
(3,)


----

#### 4.4.7 합과 평균

In [38]:
print(x)
print(nd.sum(x))


[1. 1. 1.]
<NDArray 3 @cpu(0)>

[3.]
<NDArray 1 @cpu(0)>


In [39]:
print(A)
print(nd.sum(A))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
<NDArray 5x4 @cpu(0)>

[190.]
<NDArray 1 @cpu(0)>


In [40]:
print(nd.mean(A))
print(nd.sum(A) / A.size)


[9.5]
<NDArray 1 @cpu(0)>

[9.5]
<NDArray 1 @cpu(0)>


----

#### 4.4.8 점곱(dot product)

In [43]:
x = nd.arange(4)
y = nd.ones(4)
print(x, y, nd.dot(x, y))


[0. 1. 2. 3.]
<NDArray 4 @cpu(0)> 
[1. 1. 1. 1.]
<NDArray 4 @cpu(0)> 
[6.]
<NDArray 1 @cpu(0)>


In [45]:
nd.sum(x * y)


[6.]
<NDArray 1 @cpu(0)>

----

#### 4.4.9 행렬-벡터 곱

In [46]:
nd.dot(A, x)


[ 14.  38.  62.  86. 110.]
<NDArray 5 @cpu(0)>

----

#### 4.4.10 행렬-행렬 곱

In [47]:
B = nd.ones(shape=(4,3))
nd.dot(A, B)


[[ 6.  6.  6.]
 [22. 22. 22.]
 [38. 38. 38.]
 [54. 54. 54.]
 [70. 70. 70.]]
<NDArray 5x3 @cpu(0)>

----

#### 4.4.11 놈(norm)

In [48]:
nd.norm(x)


[3.7416573]
<NDArray 1 @cpu(0)>

In [50]:
nd.sum(nd.abs(x))


[6.]
<NDArray 1 @cpu(0)>