# Chapter 4 - THE PRELIMINARIES: A CRASHCOURSE

## 4.1 Data Manapulation

#### 4.1.1 Getting Started

In [1]:
from mxnet import nd

- NDArrays represent (possibly multi-dimensional) arrays of numerical values. <br>
  NDArrays with one axis cor- respond (in math-speak) to vectors. NDArrays with two axes correspond to matrices. <br>
  For arrays with more than two axes, mathematicians do not have special names—they simply call them **_tensors_**

In [2]:
x = nd.arange(12) 
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [3]:
x.shape

(12,)

In [4]:
x.reshape((3, 4))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

- We can invoke this capability by placing **_-1_** for the dimension that we would like NDArray to automatically infer. <br>
  In our case, instead of x.reshape((3, 4)), we could have equivalently used x.reshape((-1, 4)) or x. reshape((3, -1)).


In [5]:
x.reshape((3, -1))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [6]:
x.reshape((4, -1))


[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
<NDArray 4x3 @cpu(0)>

In [7]:
x.reshape((6, -1))


[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]]
<NDArray 6x2 @cpu(0)>

In [25]:
nd.empty((3, 4))


[[ 0.0000000e+00 -4.6566129e-10  5.9740646e+31 -8.5920236e+09]
 [ 1.1210388e-44  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]]
<NDArray 3x4 @cpu(0)>

- The empty method just grabs some memory and hands us back a matrix without setting the values of any of its entries. <br>
  his is very effcient but it means that the entries might take any arbitrary values, **_including very big ones!_**

#### 4.1.2 Operations 

In [27]:
x = nd.array([1, 2, 4, 8]) 
print(x)
y = nd.ones_like(x) * 2 
print(y)


[1. 2. 4. 8.]
<NDArray 4 @cpu(0)>

[2. 2. 2. 2.]
<NDArray 4 @cpu(0)>


In [30]:
print('x =', x) 
print('x + y', x + y) 
print('x - y', x - y) 
print('x * y', x * y) 
print('x * y', x ** y) 
print('x / y', x / y)

x = 
[1. 2. 4. 8.]
<NDArray 4 @cpu(0)>
x + y 
[ 3.  4.  6. 10.]
<NDArray 4 @cpu(0)>
x - y 
[-1.  0.  2.  6.]
<NDArray 4 @cpu(0)>
x * y 
[ 2.  4.  8. 16.]
<NDArray 4 @cpu(0)>
x * y 
[ 1.  4. 16. 64.]
<NDArray 4 @cpu(0)>
x / y 
[0.5 1.  2.  4. ]
<NDArray 4 @cpu(0)>


In [31]:
x.exp()


[2.7182817e+00 7.3890562e+00 5.4598148e+01 2.9809580e+03]
<NDArray 4 @cpu(0)>

In [33]:
x = nd.arange(12).reshape((3,4)) 
y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]) 
print(x)
print(y)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>


In [34]:
nd.dot(x, y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

#### 4.1.3 Broadcast Mechanism

In [ ]:
#### 4.1.3 Broadcast Mechanism

#### 4.1.4 indexing and Slicing

In [ ]:
#### 4.1.4 indexing and Slicing

#### 4.1.5 Saving Memory

In [ ]:
#### 4.1.5 Saving Memory

#### 4.1.6 Mutual Transformation of NDArray and Numpy

In [ ]:
#### 4.1.6 Mutual Transformation of NDArray and Numpy

____

## 4.2 Linear Algebra

#### 4.2.1 Scalars

In [ ]:
#### 4.2.1 Scalars

#### 4.2.2 Vectors

In [ ]:
#### 4.2.2 Vectors

#### 4.2.3 Length, dimensionality and shape

In [ ]:
#### 4.2.3 Length, dimensionality and shape

#### 4.2.4 Matrices

In [ ]:
#### 4.2.4 Matrices

#### 4.2.5 Tensors

In [ ]:
#### 4.2.5 Tensors

#### 4.2.6 Basic properties of tensor arithetic

In [ ]:
#### 4.2.6 Basic properties of tensor arithetic

#### 4.2.7 Sums and means

In [ ]:
#### 4.2.7 Sums and means

#### 4.2.8 Dot products

In [ ]:
#### 4.2.8 Dot products

#### 4.2.9 Matrix-vector products

In [ ]:
#### 4.2.9 Matrix-vector products

#### 4.2.10 Matrix-matrix multiplication

In [ ]:
#### 4.2.10 Matrix-matrix multiplication

#### 4.2.11 Norms

In [ ]:
#### 4.2.11 Norms

#### 4.2.12 Norms and objectives

In [ ]:
#### 4.2.12 Norms and objectives

#### 4.2.13 Intermediate linear algebra

In [ ]:
#### 4.2.13 Intermediate linear algebra

#### 4.2.14 Summary

In [ ]:
#### 4.2.14 Summary

____

## 4.3 Automatic Differentiation

#### 4.3.1 A simple Example

In [ ]:
#### 4.3.1 A simple Example

#### 4.3.2 Backward for Non-scalar Variable

In [ ]:
#### 4.3.2 Backward for Non-scalar Variable

#### 4.3.3 Detach Computations

In [ ]:
#### 4.3.3 Detach Computations

#### 4.3.4 Attach Gradients to Internal Variables

In [ ]:
#### 4.3.4 Attach Gradients to Internal Variables

#### 4.3.5 Head gradients

In [ ]:
#### 4.3.5 Head gradients

#### 4.3.6 Computing the Gradient of Python Control Flow

In [ ]:
#### 4.3.6 Computing the Gradient of Python Control Flow

#### 4.3.7 Training Mode and Prediction Mode 

In [ ]:
#### 4.3.7 Training Mode and Prediction Mode 

#### 4.3.8 Summary


In [ ]:
#### 4.3.8 Summary

#### 4.3.9 Exercises

In [ ]:
#### 4.3.9 Exercises

____

## 4.4 Probability and Statistics

#### 4.4.1 Basic probability theory 

In [ ]:
#### 4.4.1 Basic probability theory 

#### 4.4.2 Dealing with multiple random variables

In [ ]:
#### 4.4.2 Dealing with multiple random variables

#### 4.4.3 Conditional independence 

In [ ]:
#### 4.4.3 Conditional independence 

#### 4.4.4 Sampling 

In [ ]:
#### 4.4.4 Sampling 

#### 4.4.5 Summary 

In [ ]:
#### 4.4.5 Summary 

#### 4.4.6 Exercises

In [ ]:
#### 4.4.6 Exercises

____

## 4.5 Naive Bayes Classiication

#### 4.5.1 Optical Character Recognition

In [ ]:
#### 4.5.1 Optical Character Recognition

#### 4.5.2 The Probabilistic Model for Classiication 

In [ ]:
#### 4.5.2 The Probabilistic Model for Classiication 

#### 4.5.3 The Naive Bayes Classiier 

In [ ]:
#### 4.5.3 The Naive Bayes Classiier 

#### 4.5.4 Training

In [ ]:
#### 4.5.4 Training

#### 4.5.5 Summary

In [ ]:
#### 4.5.5 Summary

#### 4.5.6 Exercises

In [ ]:
#### 4.5.6 Exercises

____

## 4.6 Documentation

#### 4.6.1 Finding all the functions and classes in the module 

In [ ]:
#### 4.6.1 Finding all the functions and classes in the module 

#### 4.6.2 Finding the usage of speciic functions and classes 

In [ ]:
#### 4.6.2 Finding the usage of speciic functions and classes 

#### 4.6.3 API Documentation 

In [ ]:
#### 4.6.3 API Documentation 

#### 4.6.4 Exercise 

- Look up ones_like and autograd in the API documentation. 